// Poniższe sentencje są użyte w samouczku gry.
// Jeżeli pojawią się nowe sentencje, zostaną one dodane z numerem "wersji".
// Tłumaczenie: Marek Szumny (https://peakd.com/@lukmarcus/)

// ===============================================

// VER 0.2a 

[{"intro1_welcome1":"Witaj w EXODE Ewakuacja!"},
{"intro1_welcome2":"Twoje załoga czeka na nowe rozkazy, lepiej tego nie spapraj."},
{"intro1_welcome3":"W Ewakuacji poznasz ostatnie chwile ziemskiej cywilizacji. Zdesperowana ludzkość jest znana z paniki."},
{"intro1_welcome4":"Jestem tutaj, aby ci pomóc!"},
{"intro1_welcome5":"Mogę to zrobić, chociaż jestem tylko skryptem samouczka. Czy nie jest to niesamowite? :)"},
{"intro1_welcome6":"Wiem, wiem, od razu czujesz się lepiej. Dobrze, weź głęboki oddech."},
{"intro1_welcome7":"Na początek najważniejsze: gra nie jest zapauzowana. Powtarzam: "},
{"intro1_welcome8":"gra nie jest zapauzowana."},
{"intro1_welcome9":"Dlatego właśnie wzięcie oddechu jest takie ważne. Dzięki temu mamy o 84% większe szanse na sukces."},
{"intro1_welcome10":"Pójdzie nam o wiele szybciej, jeśli nie będziesz panikować. Przejdźmy do szybkiego instruktażu!"},
{"intro1_welcome11":"Jesteśmy teraz w kokpicie. Przedstawiam ci [nameOfCrew] - to jeden z członków twojej załogi. Podwładnych masz więcej, a niektórzy z nich mogą być oficerami."},
{"intro1_welcome12":"Każdy członek załogi posiada różne umiejętności. Być może jeszcze nie wiesz, co potrafią robić, ale spokojnie, to normalne."},
{"intro1_welcome13":"W którymś momencie mogę poprosić cię o znalezienie kogoś do naprawy hipernapędu."},
{"intro1_welcome14":"Jeżeli tego nie zrobisz... Cóż, twój statek może eksplodować."},
{"intro1_welcome15":"A ludzie raczej tego nie lubią. Eksplodowania."},
{"intro1_welcome16":"Będziesz wydawać rozkazy swojej załodze, bo jesteś kapitanem tego statku."},
{"intro1_welcome17":"Niektórzy członkowie twojej załogi mogą być [b]niedostępni[/b]. Jeżeli ich komunikatory są włączone, możesz ich przywołać. Jeśli tego nie zrobisz, sami się nie zgłoszą zajęci swoimi sprawami. To jest problem."},
{"intro1_welcome18":"Jeżeli komunikatory podwładnych są wyłączone, najlepszym rozwiązaniem jest wysłanie kogoś do zbadania sprawy."},
{"intro1_welcome19":"Możesz też nie reagować i zostawić ich na pewną śmierć - a może pojawią się z powrotem, gdy usłyszą alarm?"},
{"intro1_welcome20":"W Ewakuacji musisz wykonać trzy rzeczy:"},
{"intro1_welcome21":"1. Załaduj paliwo"},
{"intro1_welcome22":"2. Ulepsz hipernapęd"},
{"intro1_welcome23":"3. Opcjonalnie: Załaduj ładunek i pasażerów."},
{"intro1_welcome24":"Proste, prawda?"},
{"intro1_welcome25":"Aby tego dokonać, będzie trzeba wydać kilka rozkazów."},
{"intro1_welcome26":"W tej sytuacji konieczne może być również [i]pilnowanie korytarzy transportowych[/i] (aby powstrzymać inwazję na twój statek, ponieważ są one bardzo pożądane)."},
{"intro1_welcome27":"Albo wysłanie kogoś do kokpitu, aby [i]zarządzać osłonami[/i], gdyby na zewnątrz zrobiło się gorąco."},
{"intro1_welcome28":"Ah, trening w Ewakuacji mówi nam, że niektórzy ludzie mogą panikować i walczyć o zapasy."},
{"intro1_welcome29":"Nawet twoja ekipa ładunkowa może napotkać agresywne wrogie załogi."},
{"intro1_welcome30":"Tak, to właśnie ludzkość."},
{"intro1_welcome31":"Może już zacznijmy, zanim tu umrzesz?"},
{"intro1_welcome32":"Aktywujemy rozkazy na jednym członku twojej załogi."},
{"intro2_orders1":"Twoja załoga czeka na nowe rozkazy."},
{"intro2_orders2":"Pierwszy rozkaz pokazuje nam listę kontrolną Ewakuacji: paliwo, ładunek, hipernapęd, pasażerowie."},
{"intro2_orders3":"Teraz klikniemy ten przycisk!"},
{"intro2_orders4":"Masz teraz dostęp do listy rozkazów niezbędnych do uruchomienia swojego statku. Przyjrzyjmy się im pokrótce."},
{"intro2_orders5":"Ten rozkaz wysyła twoją załogę do ładowni, gdzie będą ładować nowe skrzynie na twój statek."},
{"intro2_orders6":"Ładowanie załadunku jest proste, ale wymaga podstawowej Zręczności, Szybkości i Świadomości."},
{"intro2_orders7":"Nie zawsze znasz te statystyki, ale wiesz o jednej kwalifikacji, manualnym teście kwalifikacji (testują to wszyscy członkowie załogi), która pasuje większości z nich."},
{"intro2_orders8":"Ten rozkaz jest używany do wymiany i ładowania ogniw paliwowych."},
{"intro2_orders9":"Przydadzą się tu Zdolności manualne czy Szybkość, ale także Cybernetyka. Są różne techniki poszukiwania zamiennych ogniw, ich wymieniania czy szybszego ładowania."},
{"intro2_orders10":"Ten rozkaz jest niezwykle ważny. Jego celem jest przeprogramowanie twojego hipernapędu do skoku galaktycznego."},
{"intro2_orders11":"Twoja załoga nie może być nawet pewna wyników. Umiejętności niezbędne do tego zadania to Mechanika i Cybernetyka."},
{"intro2_orders12":"Aby móc przywitać nowych pasażerów, musisz zapewnić im bezpieczeństwo na pokładzie twojego statku."},
{"intro2_orders13":"Najpierw klikasz rozkaz, a potem wybierasz cywila."},
{"intro2_orders14":"Aby to zrobić, musisz być w korytarzu transportowym, a to z pewnością nie zadowoli obecnych tam ludzi"},
{"intro2_orders15":"Do uspokojenia wzburzonych cywili twoja załoga może użyć Konwersacji. Tą akcją celujesz w osobę."},
{"intro2_orders16":"Zazwyczaj trochę Empatii pomaga w osiągnięciu lepszych rezultatów. Jest ona częścią rangi Konwersacji twojej załogi."},
{"intro2_orders17":"Dodatkowo dzięki tej akcji jesteś w stanie dowiedzieć się o wiele więcej o wybranym cywilu."},
{"intro2_orders18":"Teraz wróćmy do podstawowych rozkazów."},
{"intro3_basicOrders1":"Podstawowe rozkazy to takie, które są związane z pomieszczeniem, w którym aktualnie przebywasz."},
{"intro3_basicOrders2":"Ten rozkaz wysyła członka załogi do korytarza transportowego, gdzie przygotuje się do obrony i ochrony twojego statku przed intruzami."},
{"intro3_basicOrders3":"Ten rozkaz służy do ponownego połączenia się z twoją załogą."},
{"intro3_basicOrders4":"Oznacza to powrót członka załogi jeżeli jest nieobecny lub poszukiwanie innego członka załogi po jego wskazaniu."},
{"intro3_basicOrders5":"Ten rozkaz jest używany do przemieszczania się pomiędzy różnymi pomieszczeniami."},
{"intro3_basicOrders6":"Kokpit daje dostęp do specjalnych rozkazów, takich jak prywatne akta członków załogi czy też osłony statku."},
{"intro3_basicOrders7":"Inne pomieszczenia też są specyficzne - dla przykładu pasażerów można znaleźć wyłącznie w korytarzach transportowych!"},
{"intro3_basicOrders8":"... Myślę, że dalej dasz już sobie radę!"},
{"intro3_basicOrders9":"Twoje szanse przetrwania wynoszą teraz mniej niż 10%, dlatego przeniosę się szybko w jakieś bezpieczniejsze miejsce."},
{"intro3_basicOrders10":"Powodzenia!"}]
